---
engines:
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  fixme:
    enabled: true
  radon:
    enabled: false
ratings:
  paths:
  - "**.coffee"
  - "**.py"
